# Generated by Django 4.2.7 on 2025-07-03 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(default='School Event Management System', max_length=200)),
                ('school_logo', models.URLField(blank=True, help_text='URL to school logo image', null=True)),
                ('school_address', models.TextField(blank=True)),
                ('school_phone', models.CharField(blank=True, max_length=15)),
                ('school_email', models.EmailField(blank=True, max_length=254)),
                ('allow_self_registration', models.BooleanField(default=False)),
                ('default_event_duration', models.PositiveIntegerField(default=60, help_text='Default event duration in minutes')),
                ('primary_color', models.CharField(default='#3B82F6', help_text='Primary brand color (hex)', max_length=7)),
                ('secondary_color', models.CharField(default='#10B981', help_text='Secondary brand color (hex)', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'School Settings',
                'verbose_name_plural': 'School Settings',
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('event_manager', 'Event Manager'), ('team_manager', 'Team Manager'), ('student', 'Student')], default='student', max_length=20),
        ),
    ]
