# Generated by Django 4.2.7 on 2025-07-05 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_add_chest_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolsettings',
            name='first_place_points',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='max_team_size',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='min_team_size',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='participation_points',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='second_place_points',
            field=models.PositiveIntegerField(default=6),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='third_place_points',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='schoolsettings',
            name='default_event_duration',
            field=models.PositiveIntegerField(default=7, help_text='Default event duration in days'),
        ),
        migrations.AlterField(
            model_name='schoolsettings',
            name='school_logo',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schoolsettings',
            name='school_name',
            field=models.CharField(default='School Name', max_length=200),
        ),
        migrations.AlterField(
            model_name='schoolsettings',
            name='school_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
