# Generated by Django 4.2.7 on 2025-07-22 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_user_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolsettings',
            name='school_logo',
            field=models.ImageField(blank=True, null=True, upload_to='school_logos/'),
        ),
    ]
