# Generated by Django 4.2.7 on 2025-07-03 01:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motto', models.CharField(blank=True, max_length=200)),
                ('color_code', models.CharField(default='#3B82F6', max_length=7)),
                ('logo_url', models.URLField(blank=True)),
                ('events_participated', models.PositiveIntegerField(default=0)),
                ('events_won', models.PositiveIntegerField(default=0)),
                ('current_rank', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='events.team')),
            ],
        ),
        migrations.CreateModel(
            name='PointsRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField()),
                ('point_type', models.CharField(choices=[('event_winner', 'Event Winner'), ('event_runner_up', 'Event Runner Up'), ('event_participation', 'Event Participation'), ('manual_bonus', 'Manual Bonus'), ('manual_penalty', 'Manual Penalty'), ('achievement', 'Special Achievement')], max_length=20)),
                ('reason', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('awarded_at', models.DateTimeField(auto_now_add=True)),
                ('awarded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awarded_points', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='points_records', to='events.event')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='points_records', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='points_records', to='events.team')),
            ],
            options={
                'ordering': ['-awarded_at'],
            },
        ),
    ]
