# Generated by Django 4.2.7 on 2025-07-03 04:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0002_teamprofile_pointsrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('hs', 'High School'), ('hss', 'Higher Secondary School'), ('open', 'Open Category')], default='open', max_length=10)),
                ('type', models.CharField(choices=[('cultural', 'Cultural'), ('academic', 'Academic'), ('sports', 'Sports'), ('arts', 'Arts'), ('literary', 'Literary'), ('technical', 'Technical'), ('other', 'Other')], default='other', max_length=20)),
                ('is_team_based', models.BooleanField(default=False)),
                ('max_participants', models.PositiveIntegerField(blank=True, null=True)),
                ('team_size_min', models.PositiveIntegerField(blank=True, null=True)),
                ('team_size_max', models.PositiveIntegerField(blank=True, null=True)),
                ('venue', models.CharField(blank=True, max_length=200)),
                ('scheduled_time', models.DateTimeField(blank=True, null=True)),
                ('duration', models.PositiveIntegerField(blank=True, help_text='Duration in minutes', null=True)),
                ('winner_points', models.PositiveIntegerField(default=50)),
                ('runner_up_points', models.PositiveIntegerField(default=30)),
                ('participation_points', models.PositiveIntegerField(default=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='events.event')),
            ],
            options={
                'ordering': ['scheduled_time', 'name'],
                'unique_together': {('event', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ProgramResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('position', models.PositiveIntegerField(blank=True, null=True)),
                ('points_earned', models.PositiveIntegerField(default=0)),
                ('entered_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comments', models.TextField(blank=True)),
                ('entered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entered_results', to=settings.AUTH_USER_MODEL)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_results', to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='events.program')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='program_results', to='events.team')),
            ],
            options={
                'ordering': ['position', '-marks'],
                'unique_together': {('program', 'participant')},
            },
        ),
        migrations.CreateModel(
            name='ProgramAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_programs', to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='events.program')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_assignments', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='program_assignments', to='events.team')),
            ],
            options={
                'unique_together': {('program', 'student')},
            },
        ),
    ]
