# Generated by Django 4.2.7 on 2025-07-03 14:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0004_alter_team_unique_together_alter_team_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='team_manager',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'team_manager'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_teams', to=settings.AUTH_USER_MODEL),
        ),
    ]
