# Generated by Django 4.2.7 on 2025-07-03 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_team_team_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='team_password',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='team',
            name='team_username',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
