# Generated by Django 4.2.7 on 2025-07-03 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_team_team_password_team_team_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='program',
            options={'ordering': ['start_time', 'name']},
        ),
        migrations.RenameField(
            model_name='program',
            old_name='scheduled_time',
            new_name='end_time',
        ),
        migrations.RemoveField(
            model_name='program',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='program',
            name='participation_points',
        ),
        migrations.RemoveField(
            model_name='program',
            name='runner_up_points',
        ),
        migrations.RemoveField(
            model_name='program',
            name='type',
        ),
        migrations.RemoveField(
            model_name='program',
            name='winner_points',
        ),
        migrations.AddField(
            model_name='program',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='program',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
