# Generated by Django 4.2.7 on 2025-07-04 00:56

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0008_add_chest_number_system'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programresult',
            options={'ordering': ['position', '-average_marks', '-total_marks']},
        ),
        migrations.AddField(
            model_name='programresult',
            name='average_marks',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Average marks from both judges', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='programresult',
            name='judge1_marks',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Marks out of 100 from Judge 1', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='programresult',
            name='judge2_marks',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Marks out of 100 from Judge 2', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='programresult',
            name='total_marks',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Combined marks from both judges', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='programresult',
            name='marks',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Legacy marks field', max_digits=5, null=True),
        ),
        migrations.CreateModel(
            name='JudgeScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judge', models.CharField(choices=[('judge1', 'Judge 1'), ('judge2', 'Judge 2')], max_length=10)),
                ('marks', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('criteria_scores', models.JSONField(blank=True, default=dict, help_text='Detailed scoring breakdown')),
                ('comments', models.TextField(blank=True)),
                ('entered_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entered_judge_scores', to=settings.AUTH_USER_MODEL)),
                ('program_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judge_scores', to='events.programresult')),
            ],
            options={
                'ordering': ['judge', '-marks'],
                'unique_together': {('program_result', 'judge')},
            },
        ),
    ]
