# Generated by Django 4.2.7 on 2025-07-05 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_fix_remaining_event_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='programresult',
            name='judge3_marks',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
