# Generated by Django 4.2.7 on 2025-07-05 14:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0014_add_result_numbering'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='programresult',
            options={'ordering': ['-average_marks', '-total_marks']},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='event',
            name='is_team_based',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='programresult',
            name='average_marks',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='programresult',
            name='entered_by',
            field=models.ForeignKey(blank=True, db_column='entered_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entered_results', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='programresult',
            name='judge1_marks',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='programresult',
            name='judge2_marks',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='programresult',
            name='marks',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='programresult',
            name='participant',
            field=models.ForeignKey(db_column='participant_id', on_delete=django.db.models.deletion.CASCADE, related_name='program_results', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='programresult',
            name='points_earned',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='programresult',
            name='position',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='programresult',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.team'),
        ),
        migrations.AlterField(
            model_name='programresult',
            name='total_marks',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.DeleteModel(
            name='JudgeScore',
        ),
    ]
