# Generated by Django 4.2.7 on 2025-07-12 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_remove_captain_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='event',
        ),
    ]
