# Generated by Django 4.2.7 on 2025-07-14 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_remove_team_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='max_participants_per_team',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
