# Generated by Django 4.2.7 on 2025-07-18 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0020_program_max_participants_per_team'),
    ]

    operations = [
        migrations.RenameField(
            model_name='program',
            old_name='team_size_max',
            new_name='team_size',
        ),
        migrations.RemoveField(
            model_name='program',
            name='team_size_min',
        ),
    ]
