# Generated by Django 4.2.7 on 2025-07-22 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0021_replace_team_size_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='program_type',
            field=models.CharField(choices=[('stage', 'Stage'), ('off_stage', 'Off Stage')], default='stage', max_length=20),
        ),
    ]
