steps:
  # Build the backend container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/eventloo-backend:latest', 'backend/']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/eventloo-backend:latest']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'eventloo-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/eventloo-backend:latest'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'
      - '--max-instances'
      - '5'
      - '--timeout'
      - '600'
      - '--min-instances'
      - '0'
      - '--set-env-vars'
      - 'DEBUG=False,DJANGO_SETTINGS_MODULE=event_management.settings,PYTHONUNBUFFERED=1,SECRET_KEY=django-insecure-backend-key,ALLOWED_HOSTS=eventloo-backend-241540993150.us-central1.run.app;eventloo-backend-uj5wj7uv4a-uc.a.run.app'
      - '--execution-environment'
      - 'gen2'

images:
  - 'gcr.io/$PROJECT_ID/eventloo-backend:latest'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8' 