steps:
  # Build the frontend container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/eventloo-frontend:latest', 'frontend/']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/eventloo-frontend:latest']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'eventloo-frontend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/eventloo-frontend:latest'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--memory'
      - '1Gi'
      - '--cpu'
      - '1'
      - '--max-instances'
      - '10'
      - '--timeout'
      - '300'
      - '--min-instances'
      - '0'
      - '--set-env-vars'
      - 'REACT_APP_API_URL=https://eventloo-backend-326693416937.us-central1.run.app/api'
      - '--execution-environment'
      - 'gen2'

images:
  - 'gcr.io/$PROJECT_ID/eventloo-frontend:latest'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8' 