steps:
  # Build the frontend
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/eventloo-frontend', './frontend']
    dir: '.'

  # Push the image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/eventloo-frontend']

  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'eventloo-frontend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/eventloo-frontend'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--max-instances'
      - '10'
      - '--timeout'
      - '300'
      - '--set-env-vars'
      - 'REACT_APP_API_URL=https://eventloo-backend-7vxrwvifna-uc.a.run.app,NODE_ENV=production'

images:
  - 'gcr.io/$PROJECT_ID/eventloo-frontend'

options:
  logging: CLOUD_LOGGING_ONLY 