steps:
  # Build and deploy backend
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/eventloo-backend', './backend']
    dir: 'backend'

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/eventloo-backend']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'eventloo-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/eventloo-backend'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--memory'
      - '1Gi'
      - '--cpu'
      - '1'
      - '--max-instances'
      - '10'
      - '--timeout'
      - '300'
      - '--set-env-vars'
      - 'DEBUG=False,DJANGO_SETTINGS_MODULE=event_management.settings,SECRET_KEY=eventloo-production-secret-key-2024-change-this-in-production,ALLOWED_HOSTS=localhost,127.0.0.1,eventloo-backend-7vxrwvifna-uc.a.run.app,CORS_ALLOWED_ORIGINS=https://eventloo-frontend-326693416937.us-central1.run.app'
      - '--set-env-vars'
      - 'DATABASE_URL=postgresql://eventloo_user:eventloo_secure_password_2024@/eventloo_db?host=/cloudsql/eventloo:us-central1:eventloo-instance'

  # Build and deploy frontend
  - name: 'node:16'
    entrypoint: npm
    args: ['install']
    dir: 'frontend'

  - name: 'node:16'
    entrypoint: npm
    args: ['run', 'build']
    dir: 'frontend'
    env:
      - 'REACT_APP_API_URL=https://eventloo-backend-7vxrwvifna-uc.a.run.app/api'
      - 'NODE_ENV=production'

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/eventloo-frontend', '.']
    dir: 'frontend'

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/eventloo-frontend']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'eventloo-frontend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/eventloo-frontend'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '80'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--max-instances'
      - '10'
      - '--timeout'
      - '300'
      - '--set-env-vars'
      - 'REACT_APP_API_URL=https://eventloo-backend-7vxrwvifna-uc.a.run.app/api,NODE_ENV=production'

  # Create admin user
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: curl
    args:
      - '-X'
      - 'POST'
      - 'https://eventloo-backend-7vxrwvifna-uc.a.run.app/api/create-admin-user/'
      - '-H'
      - 'Content-Type: application/json'
      - '-d'
      - '{"email":"admin@eventloo.com","password":"admin123","first_name":"Admin","last_name":"User"}'

images:
  - 'gcr.io/$PROJECT_ID/eventloo-backend'
  - 'gcr.io/$PROJECT_ID/eventloo-frontend'

options:
  logging: CLOUD_LOGGING_ONLY 