#!/bin/bash

echo "🔍 GETTING YOUR DATABASE DETAILS"
echo "=================================================="

echo "📋 Your Database Information (from our previous setup):"
echo ""
echo "🌐 Google Cloud SQL Console:"
echo "   URL: https://console.cloud.google.com/sql/instances"
echo "   Project: 7vxrwvifna"
echo "   Instance: eventloo-db"
echo ""

echo "📊 Your Database Details:"
echo "   IP Address: 35.194.18.12"
echo "   Database Name: eventloo_db"
echo "   Username: eventloo_user"
echo "   Password: eventloo_secure_password_2024"
echo "   Port: 5432"
echo ""

echo "🔗 Your DATABASE_URL:"
echo "   postgres://eventloo_user:eventloo_secure_password_2024@35.194.18.12:5432/eventloo_db"
echo ""

echo "📋 HOW TO VERIFY YOUR DATABASE:"
echo "=================================================="
echo "1. Go to: https://console.cloud.google.com/sql/instances"
echo "2. Click on: eventloo-db"
echo "3. Check:"
echo "   - OVERVIEW tab: Public IP address"
echo "   - DATABASES tab: Database name"
echo "   - USERS tab: Username and password"
echo ""

echo "🧪 TEST YOUR DATABASE CONNECTION:"
echo "=================================================="
echo "After adding DATABASE_URL to your backend, test with:"
echo ""
echo "curl -X POST -H \"Content-Type: application/json\" \\"
echo "  -d '{\"username\": \"admin\", \"password\": \"admin123\", \"email\": \"admin@eventloo.com\", \"first_name\": \"Admin\", \"last_name\": \"User\", \"role\": \"admin\"}' \\"
echo "  \"https://eventloo-backend-7vxrwvifna-uc.a.run.app/api/create-admin-user/\""
echo ""

echo "✅ EXPECTED RESULT:"
echo "   {\"message\":\"Admin user created successfully\",...}"
echo ""

echo "❌ IF IT FAILS:"
echo "   - Check that DATABASE_URL is correct"
echo "   - Verify Cloud SQL instance is running"
echo "   - Check database user credentials"
echo ""

echo "🌐 QUICK LINKS:"
echo "=================================================="
echo "🔗 Cloud SQL Console: https://console.cloud.google.com/sql/instances"
echo "🔗 Cloud Run Console: https://console.cloud.google.com/run"
echo "🔗 Your Backend: https://eventloo-backend-7vxrwvifna-uc.a.run.app" 