[build]
builder = "nixpacks"

[deploy]
startCommand = "python manage.py migrate && gunicorn event_management.wsgi:application --bind 0.0.0.0:$PORT"
healthcheckPath = "/api/admin/dashboard/summary/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
PYTHON_VERSION = "3.11.9"
DJANGO_SETTINGS_MODULE = "event_management.settings"
DEBUG = "False"
ALLOWED_HOSTS = ".railway.app"
CORS_ALLOWED_ORIGINS = "https://eventloo-frontend.railway.app"
STATIC_URL = "/static/"
STATIC_ROOT = "/opt/render/project/src/staticfiles"
MEDIA_URL = "/media/"
MEDIA_ROOT = "/opt/render/project/src/media" 