services:
  - type: web
    name: eventloo-backend
    env: python
    plan: free
    buildCommand: pip install -r backend/requirements.txt
    startCommand: ./start.sh
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: eventloo-backend.onrender.com,localhost,127.0.0.1
      - key: CORS_ALLOWED_ORIGINS
        value: https://eventloo.vercel.app,http://localhost:3000
      - key: CSRF_TRUSTED_ORIGINS
        value: https://eventloo.vercel.app,http://localhost:3000

databases:
  - name: eventloo-db
    databaseName: eventloo_db
    user: eventloo_user
    plan: free 